
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.Random;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

public class Addusers_Verifyusers_Webtable extends Orange_HRM_TestData {

	ChromeDriver driver;

	@BeforeTest
	public void launchBrowser() {

		WebDriverManager.chromedriver().setup();
		driver = new ChromeDriver();
		driver.get("https://opensource-demo.orangehrmlive.com/index.php/auth/login");
		driver.manage().window().maximize();
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	}

	/*@Test(dataProvider="LoginScenario")
	public void Login(String URL, String Uname, String Pwd) {
		driver.findElementByName("txtUsername").sendKeys("Admin");
		driver.findElementByName("txtPassword").sendKeys("admin123");
		driver.findElementById("btnLogin").click();
		driver.findElementByLinkText("Dashboard").isDisplayed();
		driver.findElementById("welcome").click();
		driver.findElement(By.xpath("//*[text()='Logout']"));
	}*/

	/*@Test
	public void addUser() {

		driver.findElement(By.id("menu_admin_viewAdminModule")).click();
		WebDriverWait wait = new WebDriverWait(driver, 30);
		wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("btnAdd")));
		driver.findElement(By.id("btnAdd")).click();
		Select role = new Select(driver.findElement(By.id("systemUser_userType")));
		role.selectByIndex(1);
		Random randomGenerator = new Random();
		int randomInt = randomGenerator.nextInt(100);
		driver.findElement(By.id("systemUser_employeeName_empName")).sendKeys("John Smith");
		driver.findElement(By.id("systemUser_userName")).sendKeys("John" + randomInt );
		driver.findElement(By.id("systemUser_userName")).getText();
		System.out.println(driver.findElement(By.id("systemUser_userName")).getText());
		driver.findElement(By.id("systemUser_password")).sendKeys("admin123");
		driver.findElement(By.id("systemUser_confirmPassword")).sendKeys("admin123");
		driver.findElement(By.id("btnSave")).click();
		System.out.println("Saved successfully!!!");
		
		
		
		//String actualLabel = driver.findElement(By.xpath("//div[text()='LOGIN Panel']")).getText();
		//Assert.assertEquals(actualLabel, "LOGIN Panel");
		
	}*/

	@AfterTest
	public void closeBrowser() {

		driver.close();
	}

}
