
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

public class loginDemo {

	ChromeDriver driver;

	@BeforeTest
	public void launchBrowser() {

		WebDriverManager.chromedriver().setup();
		driver = new ChromeDriver();
		driver.get("https://opensource-demo.orangehrmlive.com/index.php/auth/login");
		driver.manage().window().maximize();
		// driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	}

	@Test
	public void Login() {
		driver.findElementByName("txtUsername").sendKeys("Admin");
		driver.findElementByName("txtPassword").sendKeys("admin123");
		driver.findElementById("btnLogin").click();
		driver.findElementByLinkText("Dashboard").isDisplayed();
	}

	@Test
	public void logOut() {

		driver.findElement(By.id("welcome")).click();
		WebDriverWait wait = new WebDriverWait(driver, 30);
		wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//a[text()='Logout']")));
		driver.findElement(By.xpath("//a[text()='Logout']")).click();
		String actualLabel = driver.findElement(By.xpath("//div[text()='LOGIN Panel']")).getText();
		Assert.assertEquals(actualLabel, "LOGIN Panel");
		
	}

	@AfterTest
	public void closeBrowser() {

		driver.close();
	}

}
